variable "db_identifier"     { type = string }
variable "db_name"           { type = string }
variable "username"          { type = string }
variable "password"          { type = string }
variable "engine_version"    { type = string }
variable "instance_class"    { type = string }
variable "allocated_storage" { type = number }
variable "private_subnet_ids"{ type = list(string) }
variable "security_group_id" { type = string }
variable "tags"              { type = map(string) }